name: Run Jest Tests

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  test:
    runs-on: ubuntu-latest  # You can change this to macos-latest or windows-latest if needed
    strategy:
      matrix:
        node-version: [22.13.1]  # You can change or add more Node.js versions here
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: cloud
        run: npm install

      - name: Run Jest tests
        working-directory: cloud
        run: npm test

