name: Run Jest Tests

on: [push, pull_request]  # Trigger on push or pull request events

jobs:
  test:
    runs-on: ubuntu-latest  # You can change this to macos-latest or windows-latest if needed
    strategy:
      matrix:
        node-version: [22.13.1]  # You can change or add more Node.js versions here
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}  # Set Node.js version from the matrix
      
      - name: Install dependencies
        run: |
          npm install -g npm  # Ensure we use the latest npm version
          npm install         # Install project dependencies

      - name: Run Jest tests
        run: npm test    # Run the tests defined in your package.json (e.g., "test": "jest")

      - name: Upload test results
        if: success()  # Only upload test results if tests passed
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results  # Ensure your Jest results are stored in this folder or modify path accordingly
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install parse cli
        run: curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo bash

      - name: Set up Back4App CLI
        run: |
          echo "$B4A_ACCOUNT_KEY" | b4a configure accountkey
        env:
          B4A_ACCOUNT_KEY: ${{ secrets.B4A_ACCOUNT_KEY }}

      - name: Init Back4App project config
        run: |
          mkdir -p .back4app
          echo '{
            "appId": "${{ secrets.B4A_APP_ID_DEV }}",
            "appName": "MyApp",
            "language": "JavaScript",
            "version": "1.0.0"
          }' > .back4app/project.json
          
      - name: Deploy to Back4App
        run: b4a deploy