name: Run Jest Tests

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  test:
    runs-on: ubuntu-latest  # You can change this to macos-latest or windows-latest if needed
    strategy:
      matrix:
        node-version: [22.13.1]  # You can change or add more Node.js versions here
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}  # Set Node.js version from the matrix
      
      - name: Install dependencies
        run: |
          npm install -g npm  # Ensure we use the latest npm version
          npm install         # Install project dependencies

      - name: Run Jest tests
        run: npm test    # Run the tests defined in your package.json (e.g., "test": "jest")

      - name: Upload test results
        if: success()  # Only upload test results if tests passed
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results  # Ensure your Jest results are stored in this folder or modify path accordingly

  deploy-dev:
    if: github.event_name == 'push'
    name: Deploy to Back4App Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Parse CLI
        run: |
          curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash
          parse --version

      - name: Create Parse config
        run: |
          mkdir -p config
          echo '{
            "applications": {
              "dev": {
                "applicationId": "${{ secrets.BACK4APP_APP_ID_DEV }}",
                "masterKey": "${{ secrets.BACK4APP_MASTER_KEY_DEV }}",
                "serverURL": "${{ secrets.BACK4APP_SERVER_URL }}"
              }
            },
            "global": "dev"
          }' > config/global.json

      - name: Deploy to Back4App Dev
        run: parse deploy


  deploy-prod:
    if: github.event_name == 'workflow_dispatch'
    name: Deploy to Back4App Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Parse CLI
        run: npm install -g parse

      - name: Create Parse config
        run: |
          mkdir -p config
          echo '{
            "applications": {
              "prod": {
                "applicationId": "${{ secrets.BACK4APP_APP_ID_PROD }}",
                "masterKey": "${{ secrets.BACK4APP_MASTER_KEY_PROD }}",
                "serverURL": "${{ secrets.BACK4APP_SERVER_URL }}"
              }
            },
            "global": "prod"
          }' > config/global.json

      - name: Deploy to Back4App Prod
        run: parse deploy